### ISSUE TITLE
Stop the credits scene with ESC

### ISSUE THREAD

**Issue by veonazzo** [crystal-bit/hacktoberfest-2020#35]
Once the game is complete, the credit list will be very long.
I would like to add the functionality to stop it and return to the main menu by pressing ESC.

**Comment by davcri** [comment]
Good idea!  

However it would be nice to stop the scene only on long-press (user needs to press and hold the button for ~300ms). 
Since this issue revolves around the credits scene, it would be nice to also update the font used in the credits scene with Boogaloo or Luckiest Guy (already present in the fonts folder).

Can I assign the issue to you?

**Comment by Andrea1141** [comment]
If it isn't a problem for @veonazzo, you can assign the issue to me.

**Comment by veonazzo** [comment]
Of course!

**Comment by davcri** [comment]
Ok, so @Andrea1141 feel free to work on this!

**Comment by Andrea1141** [comment]
Thank you very much!

**Comment by Andrea1141** [comment]
#38 Solved!
