### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by m0rp30** [crystal-bit/hacktoberfest-2020#49]
For the usability of a game / program the language localization is very important to me

**Comment by davcri** [comment]
Thanks for opening the issue @m0rp30! 

Localization is surely important for videogames.  However we still need the videogame :smile:   

Since the game is currently a work in progress, things are going to be changed, removed, etc.  
So it's better to leave localization work in the last week of the hacktoberfest when we will have a better idea of the features, texts, etc.
