### ISSUE TITLE
Enemy: implement take damage & death mechanics

### ISSUE THREAD

**Issue by davcri** [crystal-bit/hacktoberfest-2020#97]
When an enemy dies:

- it's removed from the game
- the player gains `enemy_resource.money_dropped` coins

**Comment by vclayton** [comment]
I'd love to at least get this started. I've read through the Game Design Doc about the different tower types and enemy armor. Looking at the Ammo class I see the code for exploding when hitting an enemy, so that's where I'd start. Probably by calling a `take_damage` function on the enemy the projectile collides with. Or each enemy within the splash area, for missiles.

That brings up a question though: Are all projectiles of the same type? There's just the missile at the moment. The design makes it sound like the projectile's damage characteristics are determined by what tower fired it, so I think the projectile needs a reference back to its tower to get that info at collision time. Either that or the towers need to all fire different types of projectiles, but I think having a reference back is simpler.

**Comment by davcri** [comment]
@vclayton thanks for the interest on this issue! And also for taking the time to read the game design document :)

Calling `enemy.take_damage` from the missile scene is fine :ok_hand: 
Regarding the multiple types of projectiles I would simply set a `missile.damage` property from the `Tower.fire` method.  

> Are all projectiles of the same type?

Currently yes. The only thing that changes is the damage dealt to the enemies. 

It would be nice to change missile texture and stats based on the turret that fired it, but this can be done in a separate issue since it's important to have the `take_damage` implemented ASAP. However it was a good question, so we can keep this in mind.

Regarding the implementation I think it would be better to keep the Missile independent from the Tower.  
This can be done by creating a Missile resource, like we already done for [Enemies](https://github.com/crystal-bit/hacktoberfest-2020/blob/master/scenes/enemy/enemy_resource.gd) and [Towers](https://github.com/crystal-bit/hacktoberfest-2020/blob/master/scenes/tower/tower_resource.gd).

**Comment by davcri** [comment]
@vclayton Hey sorry to bother you but do you have an ETA for this pull request? Since tomorrow is the last day of the Hacktoberfest, I would like to get this integrated in the main gameplay. If you don't have time to finish this tomorrow, I understand and I can take it. Sorry for bothering you.

PS: if you want to join the development I'll be live streaming on Twitch tomorrow on https://www.twitch.tv/crystal_bit

**Comment by FlavioFS** [comment]
Oh no! I've posted 3 pull requests for this, but didn't see the issue here though I've searched for it. I'm sorry. 😶

**Comment by FlavioFS** [comment]
I'm working on the money drop though. 😅

**Comment by davcri** [comment]
Thanks @FlavioFS for the help! 

Also thanks @vclayton and sorry for the rushed management of this issue :pray:

**Comment by vclayton** [comment]
No problem. I got distracted by some chores around the house. I'm glad to see it working. :+1:
